- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- type: Article
  id: Mantau2022
  author: Mantau, Aprinaldi Jasa and Widayat, Irawan Widi and Leu, Jenq-Shiou and
    Köppen, Mario
  title: A Human-Detection Method Based on YOLOv5 and Transfer Learning Using Thermal
    Image Data from UAV Perspective for Surveillance System
  year: '2022'
  journal: Drones
  volume: '6'
  number: '10'
  doi: 10.3390/drones6100290
  url: https://www.scopus.com/inward/record.uri?eid=2-s2.0-85140607267&doi=10.3390%2fdrones6100290&partnerID=40&md5=b1a492c99d578d53e9c847d79e6c3ac4
  publication_stage: Final
  source: Scopus
  note: 'Cited by: 32; All Open Access, Gold Open Access'
